apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: localhost:27017
  
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: statestore
# spec:
#   type: state.mongodb
#   version: v1
#   initTimeout: 5m
#   metadata:
#   - name: host
#     value: "localhost:27017"
#   - name: databaseName
#     value: "tmp"
#   - name: collection
#     value: "tmp"
#   - name: keyPrefix
#     value: none
#   - name: params
#     value: "?authSource=admin&replicaSet=rs0&directConnection=true"
  # - name: actorStateStore
  #   value: "true"

# scopes:
#   - platform-promotions-manager-player-buffer